import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/Container'
import HomeSection from '../components/HomeSection'
import HomeSubSection from '../components/HomeSubSection'
import Navbar from '../components/Navbar'
import Navlist from '../components/Navlist'
import Services from '../components/Services'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="relative h-screen snap-y w-screen snap-proximity scroll-smooth overflow-y-scroll">
      <div className=" fixed top-0 left-0 w-screen h-screen -z-[9] ">
        <div className=" fixed top-0 left-0 w-full h-screen -z-10 bg-slate-600/80 bg-[url(./bg-main.png)]  bg-cover bg-no-repeat bg-left bg-blend-overlay"/>
      </div>
      <Head>
        <title>Adazolhub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Navlist/>
      <HomeSection/>
      <HomeSubSection/>
      <Services/>
      <section id='About'>
        <div className=" bg-gradient-to-br from-[#030309] to-[#162731] w-full h-screen grid content-center justify-center text-4xl text-green-300/100 text-center">
          <h2 className='max-w-sm uppercase animate-bounce'>Page currently on building phase...</h2>

        </div>
        </section>
    </div>
  )
}
